$a = 10; 
$b = 60; 

if ($a == $b){ 
print "if true then return this \n"; 
} 
else 
{ 
   print "Equal To Operator is False\n"; 
} 

if ($a != $b)
{ 
print "if statement is true \n"; 
} 
else 
{ 
   print "not Equal To Operator is False\n"; 
} 

if ($a > $b)
{ 
print "Greater Than Operator is True\n"; 
}
else 
{ 
   print "greater than Operator is False\n"; 
} 

if ($a < $b)
{ 
print "Less Than Operator is True\n"; 
}
else 
{ 
   print "Less than Operator is False\n"; 
} 

if ($a >= $b)
{ 
print "Greater Than Equal To Operator is True\n"; 
}
else 
{ 
   print "Greater than Equal To Operator is False\n"; 
} 

if ($a <= $b)
{ 
print "Less Than Equal To Operator is True\n"; 
}
else 
{ 
   print "Less than To Operator is False\n"; 
} 

if ($a <=> $b)
{ 
print "Comparison of Operator is True\n"; 
}
else 
{ 
   print "Comparison of Operator is False\n"; 
} 
