puts "Simple assignment operator : #{a = 20}"
puts "Add & assignment operator #{a += 10}"
puts "Subtract & assignment operator  #{ a -= 10}"
puts "Multiply AND assignment operator #{a *= 10}"
puts "Divide AND assignment operator #{a /= 4}"
puts "Modulus AND assignment operator #{a %= 3}"
puts "Exponent AND assignment operator #{a **= 3}"
